// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/meigma/mock-oidc/internal/oidc"
	mock "github.com/stretchr/testify/mock"
)

// NewCallbackQueue creates a new instance of CallbackQueue. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCallbackQueue(t interface {
	mock.TestingT
	Cleanup(func())
}) *CallbackQueue {
	mock := &CallbackQueue{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CallbackQueue is an autogenerated mock type for the CallbackQueue type
type CallbackQueue struct {
	mock.Mock
}

type CallbackQueue_Expecter struct {
	mock *mock.Mock
}

func (_m *CallbackQueue) EXPECT() *CallbackQueue_Expecter {
	return &CallbackQueue_Expecter{mock: &_m.Mock}
}

// DequeueFor provides a mock function for the type CallbackQueue
func (_mock *CallbackQueue) DequeueFor(ctx context.Context, id oidc.IssuerID) (oidc.Scenario, bool, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DequeueFor")
	}

	var r0 oidc.Scenario
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, oidc.IssuerID) (oidc.Scenario, bool, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, oidc.IssuerID) oidc.Scenario); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(oidc.Scenario)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, oidc.IssuerID) bool); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, oidc.IssuerID) error); ok {
		r2 = returnFunc(ctx, id)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// CallbackQueue_DequeueFor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DequeueFor'
type CallbackQueue_DequeueFor_Call struct {
	*mock.Call
}

// DequeueFor is a helper method to define mock.On call
//   - ctx context.Context
//   - id oidc.IssuerID
func (_e *CallbackQueue_Expecter) DequeueFor(ctx any, id any) *CallbackQueue_DequeueFor_Call {
	return &CallbackQueue_DequeueFor_Call{Call: _e.mock.On("DequeueFor", ctx, id)}
}

func (_c *CallbackQueue_DequeueFor_Call) Run(run func(ctx context.Context, id oidc.IssuerID)) *CallbackQueue_DequeueFor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 oidc.IssuerID
		if args[1] != nil {
			arg1 = args[1].(oidc.IssuerID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CallbackQueue_DequeueFor_Call) Return(scenario oidc.Scenario, b bool, err error) *CallbackQueue_DequeueFor_Call {
	_c.Call.Return(scenario, b, err)
	return _c
}

func (_c *CallbackQueue_DequeueFor_Call) RunAndReturn(run func(ctx context.Context, id oidc.IssuerID) (oidc.Scenario, bool, error)) *CallbackQueue_DequeueFor_Call {
	_c.Call.Return(run)
	return _c
}
