// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/meigma/mock-oidc/internal/oidc"
	mock "github.com/stretchr/testify/mock"
)

// NewTokenVerifier creates a new instance of TokenVerifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenVerifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenVerifier {
	mock := &TokenVerifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TokenVerifier is an autogenerated mock type for the TokenVerifier type
type TokenVerifier struct {
	mock.Mock
}

type TokenVerifier_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenVerifier) EXPECT() *TokenVerifier_Expecter {
	return &TokenVerifier_Expecter{mock: &_m.Mock}
}

// Verify provides a mock function for the type TokenVerifier
func (_mock *TokenVerifier) Verify(ctx context.Context, issuer oidc.IssuerID, token oidc.SignedToken, now oidc.Instant) (oidc.ClaimSet, error) {
	ret := _mock.Called(ctx, issuer, token, now)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 oidc.ClaimSet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, oidc.IssuerID, oidc.SignedToken, oidc.Instant) (oidc.ClaimSet, error)); ok {
		return returnFunc(ctx, issuer, token, now)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, oidc.IssuerID, oidc.SignedToken, oidc.Instant) oidc.ClaimSet); ok {
		r0 = returnFunc(ctx, issuer, token, now)
	} else {
		r0 = ret.Get(0).(oidc.ClaimSet)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, oidc.IssuerID, oidc.SignedToken, oidc.Instant) error); ok {
		r1 = returnFunc(ctx, issuer, token, now)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TokenVerifier_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type TokenVerifier_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - ctx context.Context
//   - issuer oidc.IssuerID
//   - token oidc.SignedToken
//   - now oidc.Instant
func (_e *TokenVerifier_Expecter) Verify(ctx any, issuer any, token any, now any) *TokenVerifier_Verify_Call {
	return &TokenVerifier_Verify_Call{Call: _e.mock.On("Verify", ctx, issuer, token, now)}
}

func (_c *TokenVerifier_Verify_Call) Run(run func(ctx context.Context, issuer oidc.IssuerID, token oidc.SignedToken, now oidc.Instant)) *TokenVerifier_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 oidc.IssuerID
		if args[1] != nil {
			arg1 = args[1].(oidc.IssuerID)
		}
		var arg2 oidc.SignedToken
		if args[2] != nil {
			arg2 = args[2].(oidc.SignedToken)
		}
		var arg3 oidc.Instant
		if args[3] != nil {
			arg3 = args[3].(oidc.Instant)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *TokenVerifier_Verify_Call) Return(claimSet oidc.ClaimSet, err error) *TokenVerifier_Verify_Call {
	_c.Call.Return(claimSet, err)
	return _c
}

func (_c *TokenVerifier_Verify_Call) RunAndReturn(run func(ctx context.Context, issuer oidc.IssuerID, token oidc.SignedToken, now oidc.Instant) (oidc.ClaimSet, error)) *TokenVerifier_Verify_Call {
	_c.Call.Return(run)
	return _c
}
