// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/meigma/mock-oidc/internal/oidc"
	mock "github.com/stretchr/testify/mock"
)

// NewCodeStore creates a new instance of CodeStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCodeStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *CodeStore {
	mock := &CodeStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CodeStore is an autogenerated mock type for the CodeStore type
type CodeStore struct {
	mock.Mock
}

type CodeStore_Expecter struct {
	mock *mock.Mock
}

func (_m *CodeStore) EXPECT() *CodeStore_Expecter {
	return &CodeStore_Expecter{mock: &_m.Mock}
}

// Save provides a mock function for the type CodeStore
func (_mock *CodeStore) Save(ctx context.Context, code oidc.AuthorizationCode, rec oidc.CodeRecord) error {
	ret := _mock.Called(ctx, code, rec)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, oidc.AuthorizationCode, oidc.CodeRecord) error); ok {
		r0 = returnFunc(ctx, code, rec)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CodeStore_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type CodeStore_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - code oidc.AuthorizationCode
//   - rec oidc.CodeRecord
func (_e *CodeStore_Expecter) Save(ctx any, code any, rec any) *CodeStore_Save_Call {
	return &CodeStore_Save_Call{Call: _e.mock.On("Save", ctx, code, rec)}
}

func (_c *CodeStore_Save_Call) Run(run func(ctx context.Context, code oidc.AuthorizationCode, rec oidc.CodeRecord)) *CodeStore_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 oidc.AuthorizationCode
		if args[1] != nil {
			arg1 = args[1].(oidc.AuthorizationCode)
		}
		var arg2 oidc.CodeRecord
		if args[2] != nil {
			arg2 = args[2].(oidc.CodeRecord)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CodeStore_Save_Call) Return(err error) *CodeStore_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CodeStore_Save_Call) RunAndReturn(run func(ctx context.Context, code oidc.AuthorizationCode, rec oidc.CodeRecord) error) *CodeStore_Save_Call {
	_c.Call.Return(run)
	return _c
}

// Take provides a mock function for the type CodeStore
func (_mock *CodeStore) Take(ctx context.Context, code oidc.AuthorizationCode) (oidc.CodeRecord, error) {
	ret := _mock.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for Take")
	}

	var r0 oidc.CodeRecord
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, oidc.AuthorizationCode) (oidc.CodeRecord, error)); ok {
		return returnFunc(ctx, code)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, oidc.AuthorizationCode) oidc.CodeRecord); ok {
		r0 = returnFunc(ctx, code)
	} else {
		r0 = ret.Get(0).(oidc.CodeRecord)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, oidc.AuthorizationCode) error); ok {
		r1 = returnFunc(ctx, code)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CodeStore_Take_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Take'
type CodeStore_Take_Call struct {
	*mock.Call
}

// Take is a helper method to define mock.On call
//   - ctx context.Context
//   - code oidc.AuthorizationCode
func (_e *CodeStore_Expecter) Take(ctx any, code any) *CodeStore_Take_Call {
	return &CodeStore_Take_Call{Call: _e.mock.On("Take", ctx, code)}
}

func (_c *CodeStore_Take_Call) Run(run func(ctx context.Context, code oidc.AuthorizationCode)) *CodeStore_Take_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 oidc.AuthorizationCode
		if args[1] != nil {
			arg1 = args[1].(oidc.AuthorizationCode)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CodeStore_Take_Call) Return(codeRecord oidc.CodeRecord, err error) *CodeStore_Take_Call {
	_c.Call.Return(codeRecord, err)
	return _c
}

func (_c *CodeStore_Take_Call) RunAndReturn(run func(ctx context.Context, code oidc.AuthorizationCode) (oidc.CodeRecord, error)) *CodeStore_Take_Call {
	_c.Call.Return(run)
	return _c
}
