// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/meigma/mock-oidc/internal/oidc"
	mock "github.com/stretchr/testify/mock"
)

// NewRefreshTokenStore creates a new instance of RefreshTokenStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRefreshTokenStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *RefreshTokenStore {
	mock := &RefreshTokenStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RefreshTokenStore is an autogenerated mock type for the RefreshTokenStore type
type RefreshTokenStore struct {
	mock.Mock
}

type RefreshTokenStore_Expecter struct {
	mock *mock.Mock
}

func (_m *RefreshTokenStore) EXPECT() *RefreshTokenStore_Expecter {
	return &RefreshTokenStore_Expecter{mock: &_m.Mock}
}

// Save provides a mock function for the type RefreshTokenStore
func (_mock *RefreshTokenStore) Save(ctx context.Context, token oidc.RefreshToken, rec oidc.RefreshRecord) error {
	ret := _mock.Called(ctx, token, rec)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, oidc.RefreshToken, oidc.RefreshRecord) error); ok {
		r0 = returnFunc(ctx, token, rec)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RefreshTokenStore_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type RefreshTokenStore_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - token oidc.RefreshToken
//   - rec oidc.RefreshRecord
func (_e *RefreshTokenStore_Expecter) Save(ctx any, token any, rec any) *RefreshTokenStore_Save_Call {
	return &RefreshTokenStore_Save_Call{Call: _e.mock.On("Save", ctx, token, rec)}
}

func (_c *RefreshTokenStore_Save_Call) Run(run func(ctx context.Context, token oidc.RefreshToken, rec oidc.RefreshRecord)) *RefreshTokenStore_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 oidc.RefreshToken
		if args[1] != nil {
			arg1 = args[1].(oidc.RefreshToken)
		}
		var arg2 oidc.RefreshRecord
		if args[2] != nil {
			arg2 = args[2].(oidc.RefreshRecord)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RefreshTokenStore_Save_Call) Return(err error) *RefreshTokenStore_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RefreshTokenStore_Save_Call) RunAndReturn(run func(ctx context.Context, token oidc.RefreshToken, rec oidc.RefreshRecord) error) *RefreshTokenStore_Save_Call {
	_c.Call.Return(run)
	return _c
}
