// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/meigma/mock-oidc/internal/oidc"
	mock "github.com/stretchr/testify/mock"
)

// NewRequestRecorder creates a new instance of RequestRecorder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRequestRecorder(t interface {
	mock.TestingT
	Cleanup(func())
}) *RequestRecorder {
	mock := &RequestRecorder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RequestRecorder is an autogenerated mock type for the RequestRecorder type
type RequestRecorder struct {
	mock.Mock
}

type RequestRecorder_Expecter struct {
	mock *mock.Mock
}

func (_m *RequestRecorder) EXPECT() *RequestRecorder_Expecter {
	return &RequestRecorder_Expecter{mock: &_m.Mock}
}

// Record provides a mock function for the type RequestRecorder
func (_mock *RequestRecorder) Record(ctx context.Context, req oidc.CapturedRequest) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Record")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, oidc.CapturedRequest) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RequestRecorder_Record_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Record'
type RequestRecorder_Record_Call struct {
	*mock.Call
}

// Record is a helper method to define mock.On call
//   - ctx context.Context
//   - req oidc.CapturedRequest
func (_e *RequestRecorder_Expecter) Record(ctx any, req any) *RequestRecorder_Record_Call {
	return &RequestRecorder_Record_Call{Call: _e.mock.On("Record", ctx, req)}
}

func (_c *RequestRecorder_Record_Call) Run(run func(ctx context.Context, req oidc.CapturedRequest)) *RequestRecorder_Record_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 oidc.CapturedRequest
		if args[1] != nil {
			arg1 = args[1].(oidc.CapturedRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RequestRecorder_Record_Call) Return(err error) *RequestRecorder_Record_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RequestRecorder_Record_Call) RunAndReturn(run func(ctx context.Context, req oidc.CapturedRequest) error) *RequestRecorder_Record_Call {
	_c.Call.Return(run)
	return _c
}
