// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/meigma/mock-oidc/internal/oidc"
	mock "github.com/stretchr/testify/mock"
)

// NewIssuerRegistry creates a new instance of IssuerRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIssuerRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *IssuerRegistry {
	mock := &IssuerRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// IssuerRegistry is an autogenerated mock type for the IssuerRegistry type
type IssuerRegistry struct {
	mock.Mock
}

type IssuerRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *IssuerRegistry) EXPECT() *IssuerRegistry_Expecter {
	return &IssuerRegistry_Expecter{mock: &_m.Mock}
}

// Known provides a mock function for the type IssuerRegistry
func (_mock *IssuerRegistry) Known(ctx context.Context) ([]oidc.IssuerID, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Known")
	}

	var r0 []oidc.IssuerID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]oidc.IssuerID, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []oidc.IssuerID); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]oidc.IssuerID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IssuerRegistry_Known_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Known'
type IssuerRegistry_Known_Call struct {
	*mock.Call
}

// Known is a helper method to define mock.On call
//   - ctx context.Context
func (_e *IssuerRegistry_Expecter) Known(ctx interface{}) *IssuerRegistry_Known_Call {
	return &IssuerRegistry_Known_Call{Call: _e.mock.On("Known", ctx)}
}

func (_c *IssuerRegistry_Known_Call) Run(run func(ctx context.Context)) *IssuerRegistry_Known_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *IssuerRegistry_Known_Call) Return(issuerIDs []oidc.IssuerID, err error) *IssuerRegistry_Known_Call {
	_c.Call.Return(issuerIDs, err)
	return _c
}

func (_c *IssuerRegistry_Known_Call) RunAndReturn(run func(ctx context.Context) ([]oidc.IssuerID, error)) *IssuerRegistry_Known_Call {
	_c.Call.Return(run)
	return _c
}

// Materialize provides a mock function for the type IssuerRegistry
func (_mock *IssuerRegistry) Materialize(ctx context.Context, id oidc.IssuerID) (oidc.IssuerRecord, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Materialize")
	}

	var r0 oidc.IssuerRecord
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, oidc.IssuerID) (oidc.IssuerRecord, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, oidc.IssuerID) oidc.IssuerRecord); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(oidc.IssuerRecord)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, oidc.IssuerID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IssuerRegistry_Materialize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Materialize'
type IssuerRegistry_Materialize_Call struct {
	*mock.Call
}

// Materialize is a helper method to define mock.On call
//   - ctx context.Context
//   - id oidc.IssuerID
func (_e *IssuerRegistry_Expecter) Materialize(ctx interface{}, id interface{}) *IssuerRegistry_Materialize_Call {
	return &IssuerRegistry_Materialize_Call{Call: _e.mock.On("Materialize", ctx, id)}
}

func (_c *IssuerRegistry_Materialize_Call) Run(run func(ctx context.Context, id oidc.IssuerID)) *IssuerRegistry_Materialize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 oidc.IssuerID
		if args[1] != nil {
			arg1 = args[1].(oidc.IssuerID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *IssuerRegistry_Materialize_Call) Return(issuerRecord oidc.IssuerRecord, err error) *IssuerRegistry_Materialize_Call {
	_c.Call.Return(issuerRecord, err)
	return _c
}

func (_c *IssuerRegistry_Materialize_Call) RunAndReturn(run func(ctx context.Context, id oidc.IssuerID) (oidc.IssuerRecord, error)) *IssuerRegistry_Materialize_Call {
	_c.Call.Return(run)
	return _c
}
