// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/meigma/mock-oidc/internal/oidc"
	mock "github.com/stretchr/testify/mock"
)

// NewSigner creates a new instance of Signer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSigner(t interface {
	mock.TestingT
	Cleanup(func())
}) *Signer {
	mock := &Signer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Signer is an autogenerated mock type for the Signer type
type Signer struct {
	mock.Mock
}

type Signer_Expecter struct {
	mock *mock.Mock
}

func (_m *Signer) EXPECT() *Signer_Expecter {
	return &Signer_Expecter{mock: &_m.Mock}
}

// Sign provides a mock function for the type Signer
func (_mock *Signer) Sign(ctx context.Context, id oidc.IssuerID, tok oidc.Token) (oidc.SignedToken, error) {
	ret := _mock.Called(ctx, id, tok)

	if len(ret) == 0 {
		panic("no return value specified for Sign")
	}

	var r0 oidc.SignedToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, oidc.IssuerID, oidc.Token) (oidc.SignedToken, error)); ok {
		return returnFunc(ctx, id, tok)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, oidc.IssuerID, oidc.Token) oidc.SignedToken); ok {
		r0 = returnFunc(ctx, id, tok)
	} else {
		r0 = ret.Get(0).(oidc.SignedToken)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, oidc.IssuerID, oidc.Token) error); ok {
		r1 = returnFunc(ctx, id, tok)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Signer_Sign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sign'
type Signer_Sign_Call struct {
	*mock.Call
}

// Sign is a helper method to define mock.On call
//   - ctx context.Context
//   - id oidc.IssuerID
//   - tok oidc.Token
func (_e *Signer_Expecter) Sign(ctx interface{}, id interface{}, tok interface{}) *Signer_Sign_Call {
	return &Signer_Sign_Call{Call: _e.mock.On("Sign", ctx, id, tok)}
}

func (_c *Signer_Sign_Call) Run(run func(ctx context.Context, id oidc.IssuerID, tok oidc.Token)) *Signer_Sign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 oidc.IssuerID
		if args[1] != nil {
			arg1 = args[1].(oidc.IssuerID)
		}
		var arg2 oidc.Token
		if args[2] != nil {
			arg2 = args[2].(oidc.Token)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Signer_Sign_Call) Return(signedToken oidc.SignedToken, err error) *Signer_Sign_Call {
	_c.Call.Return(signedToken, err)
	return _c
}

func (_c *Signer_Sign_Call) RunAndReturn(run func(ctx context.Context, id oidc.IssuerID, tok oidc.Token) (oidc.SignedToken, error)) *Signer_Sign_Call {
	_c.Call.Return(run)
	return _c
}
