// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/meigma/mock-oidc/internal/oidc"
	mock "github.com/stretchr/testify/mock"
)

// NewKeyStore creates a new instance of KeyStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKeyStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *KeyStore {
	mock := &KeyStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// KeyStore is an autogenerated mock type for the KeyStore type
type KeyStore struct {
	mock.Mock
}

type KeyStore_Expecter struct {
	mock *mock.Mock
}

func (_m *KeyStore) EXPECT() *KeyStore_Expecter {
	return &KeyStore_Expecter{mock: &_m.Mock}
}

// PublicKeys provides a mock function for the type KeyStore
func (_mock *KeyStore) PublicKeys(ctx context.Context, id oidc.IssuerID) (oidc.JWKS, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for PublicKeys")
	}

	var r0 oidc.JWKS
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, oidc.IssuerID) (oidc.JWKS, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, oidc.IssuerID) oidc.JWKS); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(oidc.JWKS)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, oidc.IssuerID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// KeyStore_PublicKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublicKeys'
type KeyStore_PublicKeys_Call struct {
	*mock.Call
}

// PublicKeys is a helper method to define mock.On call
//   - ctx context.Context
//   - id oidc.IssuerID
func (_e *KeyStore_Expecter) PublicKeys(ctx any, id any) *KeyStore_PublicKeys_Call {
	return &KeyStore_PublicKeys_Call{Call: _e.mock.On("PublicKeys", ctx, id)}
}

func (_c *KeyStore_PublicKeys_Call) Run(run func(ctx context.Context, id oidc.IssuerID)) *KeyStore_PublicKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 oidc.IssuerID
		if args[1] != nil {
			arg1 = args[1].(oidc.IssuerID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *KeyStore_PublicKeys_Call) Return(jWKS oidc.JWKS, err error) *KeyStore_PublicKeys_Call {
	_c.Call.Return(jWKS, err)
	return _c
}

func (_c *KeyStore_PublicKeys_Call) RunAndReturn(run func(ctx context.Context, id oidc.IssuerID) (oidc.JWKS, error)) *KeyStore_PublicKeys_Call {
	_c.Call.Return(run)
	return _c
}

// SigningKey provides a mock function for the type KeyStore
func (_mock *KeyStore) SigningKey(ctx context.Context, id oidc.IssuerID) (oidc.SigningKey, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for SigningKey")
	}

	var r0 oidc.SigningKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, oidc.IssuerID) (oidc.SigningKey, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, oidc.IssuerID) oidc.SigningKey); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(oidc.SigningKey)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, oidc.IssuerID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// KeyStore_SigningKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SigningKey'
type KeyStore_SigningKey_Call struct {
	*mock.Call
}

// SigningKey is a helper method to define mock.On call
//   - ctx context.Context
//   - id oidc.IssuerID
func (_e *KeyStore_Expecter) SigningKey(ctx any, id any) *KeyStore_SigningKey_Call {
	return &KeyStore_SigningKey_Call{Call: _e.mock.On("SigningKey", ctx, id)}
}

func (_c *KeyStore_SigningKey_Call) Run(run func(ctx context.Context, id oidc.IssuerID)) *KeyStore_SigningKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 oidc.IssuerID
		if args[1] != nil {
			arg1 = args[1].(oidc.IssuerID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *KeyStore_SigningKey_Call) Return(signingKey oidc.SigningKey, err error) *KeyStore_SigningKey_Call {
	_c.Call.Return(signingKey, err)
	return _c
}

func (_c *KeyStore_SigningKey_Call) RunAndReturn(run func(ctx context.Context, id oidc.IssuerID) (oidc.SigningKey, error)) *KeyStore_SigningKey_Call {
	_c.Call.Return(run)
	return _c
}
